# Generated by Django 4.2.26 on 2025-12-02 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('Malaria', 'Malaria'), ('Urine', 'Urine Analysis'), ('Blood', 'Blood Test'), ('TB', 'Tuberculosis'), ('CBC', 'Complete Blood Count'), ('Other', 'Other')], max_length=50)),
                ('result', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='students.studentprofile')),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'lab_tech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_conducted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
